### ISSUE TITLE
Yuri error on startup

### ISSUE THREAD

**Issue by sayori34** [sayori34/dokis#69]
beginning console dump [public]
```Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "/home/sayori/dokis/dokis/yuri/Cogs/events.py", line 119, in on_message
    if message.guild.id in conf.w_tog_on:
AttributeError: 'NoneType' object has no attribute 'id'```

**Comment by tangalbert919** [comment]
😖

**Comment by sayuri3** [comment]
Were getting oofed

**Comment by tangalbert919** [comment]
This is probably fixed now.
